import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Question from "./components/footer/question/Question";
import ReduxProvider from "./utils/ReduxProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "Qasr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/fav/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/fav/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/fav/favicon-16x16.png" />
      </head>
        <body className={montserrat.className}>
          <ReduxProvider>
            <Header />
            <div className="">
              {children}
            </div>
            <Question />
            <Footer />
          </ReduxProvider>
        </body>
    </html>
  );
}